FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./

RUN npm install --legacy-peer-deps 
COPY . .
RUN npm run build
# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]]

ENV TZ=Asia/Seoul

